name: Publish Package

on:
  push:
    tags:
      - '*'

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build --if-present
      - run: NODE_AUTH_TOKEN="" npm publish --access public --provenance
        name: 📦 Publish
        continue-on-error: true